sonar.organization=madhumitha-b-git
sonar.projectKey=madhumitha-b-git_ecom
sonar.projectName=ecom
sonar.sources=.
# Exclude library dependencies (package/package_fresh) and compressed zip files from scanning
sonar.exclusions=**/package/**,**/package_fresh/**,**/*.zip,**/package_fresh_new/**
